conf/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('image/', include('image.urls')),
    path('auth/',include('user_managemant.urls')),
    path('gallery/', include('galery.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image/urls.py
from django.urls import path
from .views import home, render_image, post_image_component, like_photo, delete_comment

app_name = "image"

urlpatterns = [
    path("", home, name="home"),
    path("home/", home, name="home"),
    path("<int:image_id>/", render_image, name="render_image"),
    path("post_image/", post_image_component, name="post_image"),
    path("like/<int:post_id>/", like_photo),
    path("delete-comment/<int:comment_id>/", delete_comment, name="delete_comment"),
]

user_managemant/urls.py
from django.urls import path
from .views import user_login, register, profile, user_logout, alter_user

app_name = "auth"

urlpatterns = [
    path("log-in/", user_login, name="user_login"),
    path("register/", register, name="register"),
    path("profile/<str:username>/", profile, name="profile"),
    path("logout/", user_logout, name="user_logout"),
    path("alter_user/", alter_user, name="alter_user"),
]

conf/templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet">    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <title>Login</title>
</head>
<body>
    <div class="main-login">
        <div class="logo">
            <img src="{% static 'media/logo_texto.png' %}" alt="">
        </div>
        <div class="form">
            <form method="post" class="card-login">
                {% csrf_token %}
                <h1>LOGIN</h1>
                <div class="textfield">

                    <label for="user">Usuário</label>
                    <input type="text" name="user" placeholder="Usuário">
                </div>
                <div class="textfield">
             
                    <label for="senha">Senha</label>
                    <input type="password" name="senha" placeholder="Senha">
                </div>
                
                <input class="btn-login" type="submit" value="Login">
            </form>
        </div>
    </div>
    
</body>
</html>

conf/templates/user/profile.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet">    <meta charset="UTF-8">

    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UPIC</title>
</head>
<body>
    <div class="user-profile">
        <h1 class="profile">{{ user.username }}</h1>
        {% if request.user == user %}
        <form method="post" action="{% url 'auth:alter_user' %}" class="form">
            {% csrf_token %}
            <label class="label" for="email">EMAIL</label>
            <input type="email" name="eamail" id="" class="input" value="{{ user.email }}">
            <label class="label" for="first_name">FIRST NAME</label>
            <input type="text" class="input" value="{{ user.first_name }}" name="first_name">
            <input type="submit" value="SAVE" class="button-save">

        </form>
        {% endif %}
    </div>



    <h1 class="posts-title">my posts</h1>
    <div class="image-grid">
        
        {% for image in user_images %}
        <div class="post-container">
            <a class="user-image" href="{% url 'image:render_image' image.id %}">
                <div >
                    <img src="{{ image.image.url }}" alt="{{ image.name }}">
                </div>
            </a>
            <h4>{{ image.title }}</h4>
        </div>
        
        {% endfor %}
    </div>
</body>
</html>
{% endblock %}

conf/templates/user/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet">    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <title>UPIC</title>
</head>
<body>
    <div class="main-login">
        <div class="logo">
            <img src="{% static 'media/logo_texto.png' %}" alt="">
        </div>
        
        <div class="form card-login">
            <h1>sign in</h1>
            <form method="post">
                {% csrf_token %}
    
                <div class="textfield">
                    <label for="{{ form.first_name.id_for_label }}">NOME</label>
                    <input type="text" name="{{ form.first_name.name }}" id="{{ form.first_name.id_for_label }}" placeholder="Nome">
                    {% if form.first_name.errors %}
                    <h6>{{form.first_name.errors}}</h6>
                    {% endif %}
                </div>

                <div class="textfield">
             
                    <label for="{{ form.last_name.id_for_label }}">SOBRENOME</label>
                    <input type="text" name="{{ form.last_name.name }}" id="{{ form.last_name.id_for_label }}" placeholder="Sobrenome">
                    {% if form.last_name.errors %}
                    <h6>{{form.last_name.errors}}</h6>
                    {% endif %}
                </div>

                <div class="textfield">
                    <label for="{{ form.username.id_for_label }}">USUÁRIO</label>
                    <input type="text" name="{{ form.username.name }}" id="{{ form.username.id_for_label }}" placeholder="Nome de Usuário">
                    {% if form.username.errors %}
                    <h6>{{form.username.errors}}</h6>
                    {% endif %}
                </div>

                <div class="textfield">
                    <label for="{{ form.email.id_for_label }}">EMAIL</label>
                    <input type="email" name="{{ form.email.name }}" id="{{ form.email.id_for_label }}" placeholder="E-mail">
                    {% if form.email.errors %}
                    <h6>{{form.email.errors}}</h6>
                    {% endif %}
                </div>

                <div class="textfield">
                    <label for="{{ form.password1.id_for_label }}">SENHA</label>
                    <input type="password" name="{{ form.password1.name }}" id="{{ form.password1.id_for_label }}" placeholder="Senha">
                    {% if form.password1.errors %}
                    <h6>{{form.password1.errors}}</h6>
                    {% endif %}
                </div>

                <div class="textfield">
                    <label for="{{ form.password2.id_for_label }}">CONFIRME A SENHA</label>
                    <input type="password" name="{{ form.password2.name }}" id="{{ form.password2.id_for_label }}" placeholder="Confirme a senha">
                    {% if form.password2.errors %}
                    <h6>{{form.password2.errors}}</h6>
                    {% endif %}
                </div>
                <div class="link-register">
                    <h6>Já tem uma conta? <a href="{% url 'auth:user_login' %}">Faça login aqui</a></h6>
                </div>
                
                <input class="btn-login" type="submit" value="sign in">
            </form>

        </div>
    </div>
    
</body>
</html>

conf/templates/user/user_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet">    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <title>UPIC</title>
</head>
<body>
    <div class="main-login">
        <div class="logo">
            <img src="{% static 'media/logo_texto.png' %}" alt="">
        </div>
        <div class="form">
            <form method="post" class="card-login">
                {% csrf_token %}
                <h1>login</h1>
                <div class="textfield">

                    <label for="user">USUÁRIO</label>
                    <input type="text" name="user" placeholder="Usuário" {% if errors %} value="{{username}}" {% endif %}>
                </div>
                <div class="textfield">
             
                    <label for="senha">SENHA</label>
                    <input type="password" name="senha" placeholder="Senha">
                </div>
                <div class="link-register">
                <h6>Não tem uma conta? <a href="{% url 'auth:register' %}">Registre-se aqui</a></h6>
                </div>
                
                <input class="btn-login" type="submit" value="login">
                {% if errors %}
                <div class="errors">
                    <h6>{{errors}}</h6>
                </div>
                
                {% endif %}
            </form>
        </div>
    </div>
    
</body>
</html>