conf/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('image/', include('image.urls')),
    path('auth/',include('user_managemant.urls')),
    path('gallery/', include('galery.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image/urls.py
from django.urls import path
from .views import home, render_image, post_image_component, like_photo, delete_comment

app_name = "image"

urlpatterns = [
    path("", home, name="home"),
    path("home/", home, name="home"),
    path("<int:image_id>/", render_image, name="render_image"),
    path("post_image/", post_image_component, name="post_image"),
    path("like/<int:post_id>/", like_photo),
    path("delete-comment/<int:comment_id>/", delete_comment, name="delete_comment"),
]

image/models.py
from django.db import models
from django.contrib.auth.models import User

class Image(models.Model):
    title = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'image'

    def get_url(self):
        return self.image.url
    

    
class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.ForeignKey(Image,on_delete=models.CASCADE)

    class Meta:
        db_table = 'like'

class Comment(models.Model):
    text = models.CharField(max_length=70,blank=False, null=False)
    posted = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.ForeignKey(Image,on_delete=models.CASCADE)

    class Meta:
        db_table = 'comment'

image/views.py
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework.generics import ListCreateAPIView
from .models import Image, Like, Comment
from .serializers import (
    ImageSerializer,
    LikeSerializer,
    CommentSerializer,
    ListCommentsSerializer,
)
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.exceptions import ValidationError
from django.http import HttpResponse
import json
from django.contrib.auth.decorators import login_required
import uuid


def home(request):
    images = Image.objects.all()
    context = {"user": request.user, "images": images}
    return render(request, "home.html", context=context)


@login_required(login_url="auth:user_login")
def post_image_component(request):

    image_file =  request.FILES.get("image")
    ext = image_file.name.split('.')[-1]
    image_name = f"{uuid.uuid4()}.{ext}"
    image_file.name = image_name

    data = {
        "title": request.POST.get("name"),
        "image": image_file,
        "user": request.user.id,
    }
    serializer = ImageSerializer(data=data)
    if serializer.is_valid():
        serializer.save()
        return redirect("image:render_image", image_id=serializer.data["id"])
    return HttpResponse(json.dumps(serializer.errors))


def render_image(request, image_id):
    if request.method == "GET":
        image_object = Image.objects.get(id=image_id)
        image = {
            "image": image_object.image,
            "image_title": image_object.title,
            "image_id": image_object.id,
            "is_liked": Like.objects.filter(user=request.user, image_id=image_id),
            "comments": Comment.objects.filter(image_id=image_id).order_by("-posted"),
        }
        return render(request, "image.html", context=image)
    elif request.method == "POST":
        comment = request.POST.get("comment-field")
        user = request.user
        post = Comment.objects.create(user=user, text=comment, image_id=image_id)
        post.save()
        return redirect("image:render_image", image_id=image_id)


from django.http import JsonResponse


def like_photo(request, post_id):
    try:
        like, created = Like.objects.get_or_create(user=request.user, image_id=post_id)
        if not created:
            like.delete()
    except Exception as e:
        return JsonResponse({"error": str(e)})

    return JsonResponse({"message": "Like updated successfully"})


def delete_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    image_id = comment.image_id
    print(image_id)
    if request.user == comment.user:
        comment.delete()
        return redirect("image:render_image", image_id=image_id)
    else:
        return HttpResponse("Sem permissão para deletar esse comentário")

image/templates/home.html
{% extends "index.html" %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <meta charset="UTF-8">
    <script src="{% static 'js/home.js' %}"></script>
</head>

<body>
    <div class="image-grid">
        {% for image in images %}
            <a class="user-image" href="{% url 'image:render_image' image.id %}">
                <div class="image-container">
                    <img src="{{ image.image.url }}" alt="{{ image.title }}" class="gallery-image" data-user="{{ image.user.username }}" data-image-id="{{ image.id }}">
                </div>
            </a>
        {% endfor %}
    </div>
</body>
</html>
{% endblock %}

image/templates/image.html
{% extends "index.html" %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/image.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UPIC</title>
</head>

<body>
    <div class="image-container">
        <div class="image-title">{{ image_title }}</div>
        <img class="image" src="{{ image.url }}" alt="Image">
        <div class="like-button">
            <i id="like-heart" class="far fa-heart {% if is_liked %}fas{% endif %}"></i>
        </div>

        <form method="post" action="{% url 'image:render_image' image_id %}" class="form-comment">
            {% csrf_token %}
            <div class="type-comment">
                <input type="text" placeholder="Faça um comentário" name="comment-field" id="comment-field" class="comment-field">
                <span id="charCountMessage" style="color: red;" class="error-message"></span>
                <button type="submit" id="submitBtn" disabled class="button-comment">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M22 12l-20 12 5-12-5-12z"/></svg>
                </button>
            </div>
        </form>

        <div id="comments" class="comments">
            {% if not comments %}
            <div>
                <h1>Nenhum comentário</h1>
            </div>
            {% else %}
            {% for comment in comments %}
            <div class="comment">
                <div>
                    <strong>{{comment.user.username}} </strong>{{comment.text}}
                </div>
                {% if request.user == comment.user %}
                <form method="post" action="{% url 'image:delete_comment' comment.id %}" class="formDelete">
                    {% csrf_token %}
                    <button type="submit" class="delete-comment-button">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </form>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


    <script>
        $(document).ready(function() {
            const likeButton = document.getElementById("like-heart");
            let isLiked = likeButton.classList.contains("fas");
            const image_id = "{{ image_id }}";
            const csrfToken = "{{ csrf_token }}";

            likeButton.addEventListener("click", () => {
                $.ajax({
                    url: `/image/like/${image_id}/`,
                    type: 'POST',
                    headers: {
                        "X-CSRFToken": csrfToken,
                    },
                    success: function(data) {
                        console.log(data);
                    },
                });
                isLiked = !isLiked;
                if (isLiked) {
                    likeButton.classList.remove("far");
                    likeButton.classList.add("fas");
                } else {
                    likeButton.classList.remove("fas");
                    likeButton.classList.add("far");
                }
            });
        });
    </script>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var commentInput = document.getElementById("comment-field");
            var submitBtn = document.getElementById("submitBtn");
            var charCountMessage = document.getElementById("charCountMessage");
            var charLimit = 70;

        commentInput.addEventListener("input", function() {
            var comment = commentInput.value;
            if (comment.length > charLimit) {
                charCountMessage.textContent = "Limite de caracteres excedido.";
                submitBtn.setAttribute("disabled", "disabled");
            } else {
                charCountMessage.textContent = "";
                submitBtn.removeAttribute("disabled");
            }
        });
    });

</script>






    
</body>
</html>
{% endblock %}