conf/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('image/', include('image.urls')),
    path('auth/',include('user_managemant.urls')),
    path('gallery/', include('galery.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

galery/urls.py
from django.urls import path
from .views import render_gallery,gallery_page,create_gallery,delete_gallery

app_name = 'gallery'
urlpatterns = [
    path('', gallery_page, name='gallery-page'),
    path('<int:pk>/', render_gallery,name='render-gallery'),
    path('create/', create_gallery,name='create-gallery'),
    path('<int:pk>',delete_gallery,name='delete-gallery')
]

image/urls.py
from django.urls import path
from .views import home, render_image, post_image_component, like_photo, delete_comment

app_name = "image"

urlpatterns = [
    path("", home, name="home"),
    path("home/", home, name="home"),
    path("<int:image_id>/", render_image, name="render_image"),
    path("post_image/", post_image_component, name="post_image"),
    path("like/<int:post_id>/", like_photo),
    path("delete-comment/<int:comment_id>/", delete_comment, name="delete_comment"),
]

user_managemant/urls.py
from django.urls import path
from .views import user_login, register, profile, user_logout, alter_user

app_name = "auth"

urlpatterns = [
    path("log-in/", user_login, name="user_login"),
    path("register/", register, name="register"),
    path("profile/<str:username>/", profile, name="profile"),
    path("logout/", user_logout, name="user_logout"),
    path("alter_user/", alter_user, name="alter_user"),
]

conf/templates/home/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        
        <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="navbar-logo">
            <a href="{% url 'image:home' %}">
                <img src="{% static 'media/logo.png' %}" alt="Logo">
            </a>
        </div>
        <ul class="navbar-links">
            <button class="add-button" {% if user.is_authenticated %}onclick="openModal()" {% else %}onclick="window.location.href = '{% url 'auth:user_login' %}'"{% endif %}>                
                <span class="plus-sign">+</span>
            </button>
            <li><a href="{% url 'image:home' %}" class="link">Home</a></li>
            <li><a href="{% url 'gallery:gallery-page' %}" class="link">Gallery</a></li>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'auth:profile' request.user %}" class="link">{{ user.username }}</a>
            </li>
            <li>
                <a href="{% url 'auth:user_logout' %}" class="link">Logout</a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'auth:user_login' %}" class="link">Sign in</a>
            </li>
            {% endif %}
            
            
        </ul>
    </nav>
        <!-- Modal -->
        <div id="uploadModal" class="modal">
            <div class="modal-content">
                <span class="close" onclick="closeModal()">&times;</span>
                <form method="post" enctype="multipart/form-data" action="{% url 'image:post_image' %}" class="upload-form">
                    {% csrf_token %}
                    <div class="textfield">
                        <label for="name">Title</label>
                        <input type="text" name="name" placeholder="Description" class="title">    
                    </div>
                    <div class="textfield">
                        <label class="upload" for="image">Select file</label>
                        <input type="file" name="image"  id="image">
                    </div>
                    <input type="submit" value="Upload" class="modal-button" name="upload">
                </form>
            </div>
        </div>
    
        <script>
            function openModal() {
                var modal = document.getElementById('uploadModal');
                modal.style.display = 'flex';
            }
            
            function closeModal() {
                var modal = document.getElementById('uploadModal');
                modal.style.display = 'none';
            }
            
            window.onclick = function(event) {
                var modal = document.getElementById('uploadModal');
                if (event.target === modal) {
                    closeModal();
                }
            }
            </script>
            <div class="block-content" id="block-content">
                {% block content %}{% endblock %}
            </div>
            
</body>
</html>