conf/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('image/', include('image.urls')),
    path('auth/',include('user_managemant.urls')),
    path('gallery/', include('galery.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

galery/urls.py
from django.urls import path
from .views import render_gallery,gallery_page,create_gallery,delete_gallery

app_name = 'gallery'
urlpatterns = [
    path('', gallery_page, name='gallery-page'),
    path('<int:pk>/', render_gallery,name='render-gallery'),
    path('create/', create_gallery,name='create-gallery'),
    path('<int:pk>',delete_gallery,name='delete-gallery')
]

galery/models.py
from django.db import models
from image.models import Image
from django.contrib.auth.models import User

class Galery(models.Model):
    name = models.CharField(max_length=30)
    image = models.ManyToManyField(Image)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

galery/views.py
from django.shortcuts import render,redirect,get_object_or_404 
from django.contrib.auth.decorators import login_required
from .models import Galery
from rest_framework.generics import RetrieveDestroyAPIView
from .serializers import GallerySerializer

@login_required(login_url='auth:user_login')
def create_gallery(request):
    name = request.POST.get('name')
    gallery = Galery.objects.create(name=name,user=request.user)
    gallery.save()
    return redirect('gallery:gallery-page') 

@login_required(login_url='auth:user_login')
def gallery_page(request):
    context = {
        'gallerys' : Galery.objects.filter(user=request.user)
    }
    return render(request,'gallery.html',context=context)

def render_gallery(request, pk):
    queryset = Galery.objects.filter(user=request.user)
    context = {
        'gallery' : get_object_or_404(queryset, pk=pk)
    }
    return render(request,'image_gallery.html',context=context)

def delete_gallery(request, pk):
    queryset = Galery.objects.filter(user=request.user)
    instance = get_object_or_404(queryset, pk=pk)
    instance.delete()
    return redirect('gallery:gallery-page') 

galery/templates/gallery.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet">    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/gallery.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UPIC</title>
</head>
<body>

    <div class="container">
        <div class="title-create">
            <h1>my galleries</h1>
            <button class="gallery-add" onclick="openModalGallery()">
                <span class="add-label">+</span>
            </button>

        </div>
        
        <div class="image-grid">
            {% for gallery in gallerys %}
            <div class="user-image">
                <a href="{% url 'gallery:render-gallery' gallery.id %}">{{ gallery.name }}</a>
            <a href="{% url 'gallery:delete-gallery' gallery.id %}" class="delete-action" onclick="return confirmDelete(event, '{{ gallery.id }}')">
                <i class="fas fa-trash-alt delete-icon"></i>
            </a>
            </div>
            {% endfor %}
        </div>
    </div>

     <!-- Modal -->
     <div id="uploadModalGallery" class="modal-gallery">
        <div class="modal-content-gallery">
            <span class="close-gallery" onclick="closeModalGallery()">&times;</span>
            <form method="post" action="{% url 'gallery:create-gallery' %}" class="upload-form">
                {% csrf_token %}
                <div class="text-field">
                    <label for="name">Title</label>
                    <input type="text" name="name" placeholder="Description">    
                </div>
                <input type="submit" value="Upload" class="modal-button">
            </form>
        </div>
    </div>

    <script>
        function openModalGallery() {
            var modal = document.getElementById('uploadModalGallery');
            modal.style.display = 'flex';
        }
        
        function closeModalGallery() {
            var modal = document.getElementById('uploadModalGallery');
            modal.style.display = 'none';
        }
        
        window.onclick = function(event) {
            var modal = document.getElementById('uploadModalGallery');
            if (event.target === modal) {
                closeModalGallery();
            }
        }
        </script>

    <script>
        function confirmDelete(event, galleryId) {
        var confirmation = confirm("Tem certeza de que deseja excluir esta galeria?");
        if (confirmation) {
            window.location.href = "{% url 'gallery:delete-gallery' 0 %}".replace('0', galleryId);
        } else {
            // Impede a ação padrão do link (navegar para a URL)
            return event.preventDefault();
        }
    }
    </script>
</body>

</html>
{% endblock %}

galery/templates/image_gallery.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet">    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/image_gallery.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UPIC</title>
</head>
<body>
    <h1>GALERIA</h1>
</body>
</html>

{% endblock %}